services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: labbridge-rabbitmq
    ports:
      - "5672:5672"    # AMQP port (for LabBridge app)
      - "15672:15672"  # Management UI (web interface)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - labbridge-network

volumes:
  rabbitmq_data:
    driver: local

networks:
  labbridge-network:
    driver: bridge
