# Prometheus configuration for LabBridge metrics scraping
global:
  scrape_interval: 15s      # Scrape targets every 15 seconds
  evaluation_interval: 15s  # Evaluate rules every 15 seconds
  external_labels:
    monitor: 'labbridge-monitor'
    environment: 'development'

# Alertmanager configuration (optional - can be added later)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

# Load rules once and periodically evaluate them
# rule_files:
#   - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # LabBridge Service metrics
  - job_name: 'labbridge'
    scrape_interval: 10s      # Scrape LabBridge more frequently (10s)
    scrape_timeout: 5s
    metrics_path: '/metrics'   # Default Prometheus metrics endpoint
    static_configs:
      - targets: ['host.docker.internal:5000']  # LabBridge running on host machine
        labels:
          service: 'labbridge'
          component: 'integration-service'
          environment: 'development'
