name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run unit tests
      run: dotnet test --no-build --configuration Release --verbosity normal --logger "console;verbosity=detailed" --filter "FullyQualifiedName!~IntegrationTests"

    - name: Test Summary
      if: always()
      run: |
        echo "### Test Results :test_tube:" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Unit tests completed (64 tests). E2E integration tests run manually before releases." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**E2E Tests**: Available in tests/LabBridge.IntegrationTests" >> $GITHUB_STEP_SUMMARY
        echo "Run with: docker-compose -f tests/LabBridge.IntegrationTests/docker-compose.test.yml up -d && dotnet test" >> $GITHUB_STEP_SUMMARY
